train_logistic:
  max_iter: 200
  random_state: 31
  n_jobs: -1

train_grid_search_decision_tree:
  criterion: ['gini', 'entropy']
  max_depth: [3, 5, 7, 10]
  splitter: ['best', 'random']
  min_samples_leaf: [1, 2, 3, 5, 7]
  min_samples_split: [2, 3, 5, 7]
  max_features: ['auto', 'sqrt', 'log2']
